name: infinite_scroll
description: Rearch example application showcasing infinite scroll.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_rearch: ^1.5.2
  rearch: ^1.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
