name: flutter_rearch
description: A re-imagined declarative approach to application design and architecture
version: 1.7.2
homepage: https://rearch.gsconrad.com
documentation: https://rearch.gsconrad.com
repository: https://github.com/GregoryConrad/rearch-dart
issue_tracker: https://github.com/GregoryConrad/rearch-dart/issues
resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ">=3.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.10.0
  rearch: ^1.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
