name: flutter_rearch
description: A re-imagined declarative approach to application design and architecture
version: 1.6.13
homepage: https://rearch.gsconrad.com
documentation: https://rearch.gsconrad.com
repository: https://github.com/GregoryConrad/rearch-dart
issue_tracker: https://github.com/GregoryConrad/rearch-dart/issues

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  macros: ^0.1.3-main.0
  meta: ^1.10.0
  rearch: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
