name: flutter_rearch
description: A re-imagined declarative approach to application design and architecture
version: 1.6.7
homepage: https://rearch.gsconrad.com
documentation: https://rearch.gsconrad.com
repository: https://github.com/GregoryConrad/rearch-dart
issue_tracker: https://github.com/GregoryConrad/rearch-dart/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.10.0
  rearch: ^1.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
