name: rearch
description: A re-imagined declarative approach to application design and architecture
version: 1.5.0
homepage: https://rearch.gsconrad.com
documentation: https://rearch.gsconrad.com
repository: https://github.com/GregoryConrad/rearch-dart
issue_tracker: https://github.com/GregoryConrad/rearch-dart/issues

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.9.1

dev_dependencies:
  test: ^1.24.4
