name: react_rearch_example
publish_to: none

environment:
  sdk: ^3.3.3

dependencies:
  react: ^7.1.0
  react_rearch: ^0.0.1
  rearch: ^1.8.0+0

dev_dependencies:
  build_runner: ^2.4.9
  build_web_compilers: ^4.0.10
  lints: ^2.1.0
