name: presentation
description: Interactive presentation introducing ReArch.
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  device_frame: ^1.1.0
  flutter:
    sdk: flutter
  flutter_deck: ^0.21.0
  flutter_rearch: ^1.7.2
  graphview: ^1.2.0
  rearch: ^1.16.1
  url_strategy: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/
