name: presentation
description: Interactive presentation introducing ReArch.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  device_frame: ^1.1.0
  flutter:
    sdk: flutter
  flutter_deck: ^0.16.1
  flutter_rearch: ^1.6.8
  graphview: ^1.2.0
  rearch: ^1.10.1
  url_strategy: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/
