name: scorus
description: "Pickleball score tracker"
publish_to: none

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: '>=3.16.9 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_rearch: ^1.5.1
  rearch: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
