name: scorus
description: "Pickleball score tracker"
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: '>=3.16.9 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_rearch: ^1.7.2
  rearch: ^1.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
