name: scorus
description: "Pickleball score tracker"
publish_to: none

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: '>=3.16.9 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_rearch: ^1.6.7
  rearch: ^1.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
