name: flutter_rearch_example
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_mimir: ^0.1.0
  flutter_rearch: ^1.6.10
  mimir: ^0.1.0
  rearch: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
