name: flutter_rearch_example
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_mimir: ^0.0.2
  flutter_rearch: ^1.0.1
  mimir: ^0.0.2
  rearch: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
