name: flutter_rearch_example
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_mimir: ^0.1.6
  flutter_rearch: ^1.7.2
  mimir: ^0.1.6
  rearch: ^1.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
