name: ramen
description: A re-imagined web UI framework written around ReArch
version: 0.0.0-dev.14
homepage: https://rearch.gsconrad.com
documentation: https://rearch.gsconrad.com
repository: https://github.com/GregoryConrad/rearch-dart
issue_tracker: https://github.com/GregoryConrad/rearch-dart/issues
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  fast_immutable_collections: ^11.0.0
  meta: ^1.14.0
  rearch: ^1.16.1
  web: ^1.0.0

dev_dependencies:
  test: ^1.24.4
