name: react_rearch
description: A re-imagined declarative approach to application design and architecture
version: 0.0.1
homepage: https://rearch.gsconrad.com
documentation: https://rearch.gsconrad.com
repository: https://github.com/GregoryConrad/rearch-dart
issue_tracker: https://github.com/GregoryConrad/rearch-dart/issues

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  meta: ^1.10.0
  react: ^7.1.0
  rearch: ^1.8.0

dev_dependencies:
  test: ^1.24.4
  