name: count_warm_up
description: Rearch example application making use of warm up capsules.
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_rearch: ^1.7.2
  rearch: ^1.16.1
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
