name: Deploy ReArch Presentation to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v3
      - name: Run tests
        run: melos run test --no-select
      - name: Build for web
        run: flutter build web
        working-directory: examples/presentation
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: examples/presentation
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_REARCH_PRESENTATION }}'
          channelId: live
          projectId: rearch-presentation
