name: Publish Release(s)

on:
  push:
    tags:
      - "*"

jobs:
  publish_github_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: softprops/action-gh-release@v1

  publish_pub_release:
    # Modified from dart-lang/setup-dart/.github/workflows/publish.yml@7361df6
    runs-on: ubuntu-latest
    permissions:
      id-token: write # this is required for requesting the JWT

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v2

      - name: Dry-run publish to pub.dev
        run: melos publish -y --dry-run
      - name: Publish to pub.dev
        run: melos publish -y --no-dry-run
