name: Build & Test

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # runs the CI everyday at 10AM
    - cron: "0 10 * * *"

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v3

      - name: Check code format
        run: melos format --set-exit-if-changed
      - name: Run code analysis
        run: flutter analyze --fatal-infos --fatal-warnings
      - name: Run tests
        run: melos run test --no-select

  linux_integration_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies for flutter integration test
        run: sudo apt update && sudo apt-get install -y libglu1-mesa ninja-build clang cmake pkg-config libgtk-3-dev liblzma-dev
      - uses: pyvista/setup-headless-display-action@v3
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v3
      - name: Run integration tests
        run: melos run test:linux-integration --no-select
